#!/bin/sh
#        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004

# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>

# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.

#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

#  0. You just DO WHAT THE FUCK YOU WANT TO.

#
#
#
#
#

if test $# -lt 1 ; then
    echo "Usage: $(basename "$0") FILE [FILE...]"
    exit 1
fi
# check dependencies
DEPS="curl jq"
for dep in $DEPS; do
    if ! hash $dep >/dev/null 2>/dev/null; then
        echo "Please install $dep."
        exit 1
    fi
done

uppomf="https://pomf.lain.la/upload.php"


set=
for f ; do
    test "$set" || set -- ; set=1
    set -- "$@" -F "files[]=@$f"
done

curl -fsSL "$@" "$uppomf" | jq -c -r ".files[].url"
